name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Checking out the repo

    - name: Build and publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: pubsub-emulator # Provide Docker image name